### ISSUE TITLE
bh1730.c does not compile

### ISSUE THREAD

**Issue by AleaLabs** [mongoose-os-libs/bh1730#1]
Using the mongoose-os-apps/aws-pico repo and compiling via 'mos build', I get the following errors:

CC /fwbuild-volumes/latest/apps/aws-pico/esp32/build_contexts/build_ctx_847202644/build/objs/bt/bluedroid/bta/hh/bta_hh_main.o
/fwbuild-volumes/latest/apps/aws-pico/esp32/build_contexts/build_ctx_847202644/libs/bh1730/src/bh1730.c: In function 'bh1730_read_lux':
/fwbuild-volumes/latest/apps/aws-pico/esp32/build_contexts/build_ctx_847202644/libs/bh1730/src/bh1730.c:101:9: error: implicit declaration of function 'vTaskDelay' [-Werror=implicit-function-declaration]
         vTaskDelay(20 / portTICK_RATE_MS);
         ^
/fwbuild-volumes/latest/apps/aws-pico/esp32/build_contexts/build_ctx_847202644/libs/bh1730/src/bh1730.c:101:25: error: 'portTICK_RATE_MS' undeclared (first use in this function)
         vTaskDelay(20 / portTICK_RATE_MS);
                         ^
/fwbuild-volumes/latest/apps/aws-pico/esp32/build_contexts/build_ctx_847202644/libs/bh1730/src/bh1730.c:101:25: note: each undeclared identifier is reported only once for each function it appears in
cc1: all warnings being treated as errors
CC mgos_ca_bundle.o
make[1]: *** [bh1730.o] Error 1
/mongoose-os/fw/platforms/esp32/src/esp32_src.mk:126: recipe for target 'bh1730.o' failed

It would appear that the vTaskDelay and portTICK_RATE_MS are coming from FreeRTOS? Was this an issue of ported code? The issue is on line 101:         vTaskDelay(20 / portTICK_RATE_MS);

**Comment by adaffre** [comment]
same issue. @AleaLabs did u solve? thx

**Comment by rojer** [comment]
fixed the build. don't know if it works, but it builds now.

**Comment by adaffre** [comment]
mongoose-os remote build `mos build` fails. probably related to server caching repo.
local build `mos build --local` works cloning #2 https://github.com/mongoose-os-libs/bh1730/commit/f85b34af73e2d2e16521e1e18b148fe578d2fe4e locally and adding `- origin: ./local_libs_dir/bh1730` to `mos.yml`. testing sensor functionality.

**Comment by rojer** [comment]
this is because if you're using release version of mos, you're still using the 2.20 tag for the library.
you can selectively switch to master version of the library by adding `version: latest` to the library's entry in mos.yml:

```
libs:
  - location: https://github.com/mongoose-os-libs/bh1730
  - version: latest
```
